---
###### Install auditd #####
- name: Install audit
  ansible.builtin.package:
    name: "{{ auditd_packages }}"
    state: present

###### Modify auditd.conf for OL7 #####
- name: Configure auditd
  ansible.builtin.template:
    src: "{{ auditd_config_file_ol7 }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - Restart auditd
  when:
    - ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7"

###### Modify auditd.conf for OL8 #####
- name: Configure auditd
  ansible.builtin.template:
    src: "{{ auditd_config_file_ol8 }}.j2"
    dest: "{{ auditd_config_directory }}/{{ auditd_config_file }}"
    mode: "0640"
  notify:
    - Restart auditd
  when:
    - ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8"

 ###### Check if /etc/audit/rules.d/ exists #####
- name: Create rules.d directory
  ansible.builtin.file:
    path: "{{ auditd_config_directory }}/rules.d"
    state: directory
    mode: "0750"

 ###### Copy  rules file over to the server #####
- name: Copy file cusom rules to /etc/audit/rules.d
  copy:
    src: files/audit.rules
    dest: "/{{ auditd_config_directory }}/rules.d/audit.rules"
    follow: yes
  notify:
    - Run augenrules
  when:
    - auditd_manage_rules

###### Start auditd service#####
- name: Start and enable auditd
  ansible.builtin.service:
    name: "{{ auditd_service }}"
    state: started
    enabled: yes

###### Install audispd-plugins #####
- name: Install audispd-plugins
  ansible.builtin.package:
    name: "{{ audispd_plugins_packages }}"
    state: present

 ###### Copy syslog.conf over to OL7 #####
- name: Copy syslog.conf file cusom rules to /etc/audisp/plugins.d
  copy:
    src: files/syslog.conf
    dest: /etc/audisp/plugins.d/syslog.conf
    follow: yes
  when:
    - ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "7"

###### Copy syslog.conf over to OL8 #####
- name: Copy syslog.conf file cusom rules to /etc/audit/plugins.d/
  copy:
    src: files/syslog.conf
    dest: /etc/audit/plugins.d/syslog.conf
    follow: yes
  when:
    - ansible_distribution == "OracleLinux" and ansible_distribution_major_version == "8"

####### Modify /etc/rsyslog.conf ########
- name: change parameters in /etc/rsyslog.conf
  lineinfile: 
    path: /etc/rsyslog.conf
    backup: yes
    line: "{{ item.line }}"
    insertafter: "{{ item.insertafter }}"
    state: present
    firstmatch: yes
  with_items: 
  - { insertafter: '^#### GLOBAL DIRECTIVES ####', line: '# Filter duplicated messages' }
  - { insertafter: '^# Filter duplicated messages', line: '$RepeatedMsgReduction off' }


###### Copy audit.conf over to the server #####
- name: Copy audit.conf file to /etc/audit/plugins.d/
  copy:
    src: files/audit.conf
    dest: /etc/rsyslog.d/audit.conf
    follow: yes
  notify:
    - Restart rsyslog
